app = "trilogy-optic-shopify"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 10000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
  memory_mb = 1024

[env]
  PORT = "10000"
  NODE_ENV = "production"