name: Auto-Regenerate Shopify Bypass Link

on:
  schedule:
    - cron: '*/50 * * * *'  # Every 50 minutes
  workflow_dispatch:  # Manual trigger

jobs:
  regenerate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install
      
      - name: Regenerate bypass link
        env:
          SHOPIFY_COOKIES: ${{ secrets.SHOPIFY_COOKIES }}
          BROWSERLESS_TOKEN: ${{ secrets.BROWSERLESS_TOKEN }}
        run: node regenerate-browserless.js
      
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add index.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update bypass link [skip ci]"
          git push