name: Auto-Regenerate Shopify Bypass Link

on:
  schedule:
    # Run every 50 minutes
    - cron: '*/50 * * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  regenerate:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install puppeteer
      
      - name: Regenerate bypass link
        env:
          SHOPIFY_COOKIES: ${{ secrets.SHOPIFY_COOKIES }}
        run: node regenerate-bypass-link.js
      
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add index.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update Shopify bypass link [skip ci]"
          git push